name: builds 
on: 
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
        node:
          image: shukriadams/node8build:0.0.3    
    steps:
      - uses: actions/checkout@v1
      - name: deploys latest version of gallery
        run: docker run -e $HOST -e $USERNAME -e $PASSWORD -v $(pwd):/tmp/gallery shukriadams/node8build:0.0.3 sh -c "cd /tmp/gallery && rsync --recursive --times --compress --delete --progress --rsh="\""sshpass -p ${PASSWORD} ssh -o StrictHostKeyChecking=no -l ${USERNAME}"\"" ./*  ${USERNAME}@${HOST}:/srv/manafeed-gallery/ && sshpass -p ${PASSWORD} ssh -oStrictHostKeyChecking=no ${USERNAME}@${HOST} 'cd /srv/manafeed-gallery && docker-compose down && docker-compose up -d'"
        env:
            HOST: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}